CONTROLS:
  KEYBOARD:
    LEFT: 'KEY_LEFT'
    RIGHT: 'KEY_RIGHT'
    UP: 'KEY_UP'
    DOWN: 'KEY_DOWN'
    REVEAL: ' '
    FLAG: 'f'
    RESET: 'r'
    HOME: 'KEY_HOME'
    END: 'KEY_END'
    CEILING: 'KEY_PPAGE'
    FLOOR: 'KEY_NPAGE'
    HELP: 'h'
    EXIT: 'q'
  MOUSE:
    LEFT: NULL
    RIGHT: NULL
    UP: NULL
    DOWN: NULL
    REVEAL: 'BUTTON1_CLICKED'
    FLAG: 'BUTTON3_CLICKED'
    RESET: NULL
    HOME: NULL
    END: NULL
    CEILING: NULL
    FLOOR: NULL
    HELP: NULL
    EXIT: NULL

SETUP:
  MIN_WIDTH: 2
  MIN_HEIGHT: 2
  MAX_WIDTH: NULL
  MAX_HEIGHT: NULL
  BEGINNER:
    WIDTH: 09
    HEIGHT: 09
    RATIO: 0.123
  INTERMEDIATE:
    WIDTH: 16
    HEIGHT: 16
    RATIO: 0.156
  EXPERT:
    WIDTH: 30
    HEIGHT: 16
    RATIO: 0.206

LOOK:
  SYMBOLS:
    BLANK: ' '
    ONE: '1'
    TWO: '2'
    THREE: '3'
    FOUR: '4'
    FIVE: '5'
    SIX: '6'
    SEVEN: '7'
    EIGHT: '8'
    MINE: '¤'
    FLAG: '¶'
    UNOPENED: '■'

  COLORS:
    DEFAULT:
      ONE: 4
      TWO: 2
      THREE: 1
      FOUR: 3
      FIVE: 5
      SIX: 6
      SEVEN: 0
      EIGHT: 7
      SELECTOR: 3
      LOSE: 1
      WIN: 2

    RGB:
      ONE: [0, 0, 1000]
      TWO: [0, 500, 0]
      THREE: [1000, 0, 0]
      FOUR: [0, 0, 500]
      FIVE: [500, 0, 0]
      SIX: [0, 500, 500]
      SEVEN: [0, 0, 0]
      EIGHT: [500, 500, 500]
      SELECTOR: [1000, 1000, 0]
      LOSE: [1000, 0, 0]
      WIN: [0, 1000, 0]